{{- if or (.Values.db.enabled.crossplane.local) (.Values.db.enabled.crossplane.google) (.Values.db.enabled.crossplane.aws) (.Values.db.enabled.crossplane.azure) }}
---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQLClaim
metadata:
  name: {{ template "name" . }}
spec:
  id: {{ .Values.db.id }}
  compositionSelector:
    matchLabels:
      {{- if .Values.db.enabled.crossplane.local }}
      provider: local-k8s
      {{- end }}
      {{- if .Values.db.enabled.crossplane.google }}
      provider: google-official
      {{- end }}
      {{- if .Values.db.enabled.crossplane.azure }}
      provider: azure-official
      {{- end }}
      {{- if .Values.db.enabled.crossplane.aws }}
      provider: aws-official
      {{- end }}
      db: postgresql
  parameters:
    version: "11"
    size: small

{{- end }}
{{- if .Values.db.insecure }}
{{- if or (.Values.db.enabled.crossplane.google) (.Values.db.enabled.crossplane.azure) (.Values.db.enabled.crossplane.aws) }}
---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.id }}-password
data:
  password: T1QrOXZQcDhMdXhoeFVQWVpLSk1kUG1YM04xTzBTd3YzWG5ZVjI0UFZzcz0=
{{- end }}
{{- end }}
