package databasesschemaheroio

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"databasesschemaheroio.Database",
		reflect.TypeOf((*Database)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addDependency", GoMethod: "AddDependency"},
			_jsii_.MemberMethod{JsiiMethod: "addJsonPatch", GoMethod: "AddJsonPatch"},
			_jsii_.MemberProperty{JsiiProperty: "apiGroup", GoGetter: "ApiGroup"},
			_jsii_.MemberProperty{JsiiProperty: "apiVersion", GoGetter: "ApiVersion"},
			_jsii_.MemberProperty{JsiiProperty: "chart", GoGetter: "Chart"},
			_jsii_.MemberProperty{JsiiProperty: "kind", GoGetter: "Kind"},
			_jsii_.MemberProperty{JsiiProperty: "metadata", GoGetter: "Metadata"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberMethod{JsiiMethod: "toJson", GoMethod: "ToJson"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_Database{}
			_jsii_.InitJsiiProxy(&j.Type__cdk8sApiObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseProps",
		reflect.TypeOf((*DatabaseProps)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpec",
		reflect.TypeOf((*DatabaseSpec)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnection",
		reflect.TypeOf((*DatabaseSpecConnection)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandra",
		reflect.TypeOf((*DatabaseSpecConnectionCassandra)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraKeyspace",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraKeyspace)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraKeyspaceValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraKeyspaceValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraKeyspaceValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraKeyspaceValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraKeyspaceValueFromSsm",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraKeyspaceValueFromSsm)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraKeyspaceValueFromSsmAccessKeyId",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraKeyspaceValueFromSsmAccessKeyId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraKeyspaceValueFromSsmAccessKeyIdValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraKeyspaceValueFromSsmAccessKeyIdValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraKeyspaceValueFromSsmAccessKeyIdValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraKeyspaceValueFromSsmAccessKeyIdValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraKeyspaceValueFromSsmSecretAccessKey",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraKeyspaceValueFromSsmSecretAccessKey)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraKeyspaceValueFromSsmSecretAccessKeyValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraKeyspaceValueFromSsmSecretAccessKeyValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraKeyspaceValueFromSsmSecretAccessKeyValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraKeyspaceValueFromSsmSecretAccessKeyValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraKeyspaceValueFromVault",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraKeyspaceValueFromVault)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraPassword",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraPassword)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraPasswordValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraPasswordValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraPasswordValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraPasswordValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraPasswordValueFromSsm",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraPasswordValueFromSsm)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraPasswordValueFromSsmAccessKeyId",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraPasswordValueFromSsmAccessKeyId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraPasswordValueFromSsmAccessKeyIdValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraPasswordValueFromSsmAccessKeyIdValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraPasswordValueFromSsmAccessKeyIdValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraPasswordValueFromSsmAccessKeyIdValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraPasswordValueFromSsmSecretAccessKey",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraPasswordValueFromSsmSecretAccessKey)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraPasswordValueFromSsmSecretAccessKeyValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraPasswordValueFromSsmSecretAccessKeyValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraPasswordValueFromSsmSecretAccessKeyValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraPasswordValueFromSsmSecretAccessKeyValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraPasswordValueFromVault",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraPasswordValueFromVault)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraUsername",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraUsername)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraUsernameValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraUsernameValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraUsernameValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraUsernameValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraUsernameValueFromSsm",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraUsernameValueFromSsm)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraUsernameValueFromSsmAccessKeyId",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraUsernameValueFromSsmAccessKeyId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraUsernameValueFromSsmAccessKeyIdValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraUsernameValueFromSsmAccessKeyIdValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraUsernameValueFromSsmAccessKeyIdValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraUsernameValueFromSsmAccessKeyIdValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraUsernameValueFromSsmSecretAccessKey",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraUsernameValueFromSsmSecretAccessKey)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraUsernameValueFromSsmSecretAccessKeyValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraUsernameValueFromSsmSecretAccessKeyValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraUsernameValueFromSsmSecretAccessKeyValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraUsernameValueFromSsmSecretAccessKeyValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCassandraUsernameValueFromVault",
		reflect.TypeOf((*DatabaseSpecConnectionCassandraUsernameValueFromVault)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdb",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdb)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbDbname",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbDbname)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbDbnameValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbDbnameValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbDbnameValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbDbnameValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbDbnameValueFromSsm",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbDbnameValueFromSsm)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbDbnameValueFromSsmAccessKeyId",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbDbnameValueFromSsmAccessKeyId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbDbnameValueFromSsmAccessKeyIdValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbDbnameValueFromSsmAccessKeyIdValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbDbnameValueFromSsmAccessKeyIdValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbDbnameValueFromSsmAccessKeyIdValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbDbnameValueFromSsmSecretAccessKey",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbDbnameValueFromSsmSecretAccessKey)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbDbnameValueFromSsmSecretAccessKeyValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbDbnameValueFromSsmSecretAccessKeyValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbDbnameValueFromSsmSecretAccessKeyValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbDbnameValueFromSsmSecretAccessKeyValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbDbnameValueFromVault",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbDbnameValueFromVault)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbHost",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbHost)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbHostValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbHostValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbHostValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbHostValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbHostValueFromSsm",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbHostValueFromSsm)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbHostValueFromSsmAccessKeyId",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbHostValueFromSsmAccessKeyId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbHostValueFromSsmAccessKeyIdValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbHostValueFromSsmAccessKeyIdValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbHostValueFromSsmAccessKeyIdValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbHostValueFromSsmAccessKeyIdValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbHostValueFromSsmSecretAccessKey",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbHostValueFromSsmSecretAccessKey)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbHostValueFromSsmSecretAccessKeyValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbHostValueFromSsmSecretAccessKeyValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbHostValueFromSsmSecretAccessKeyValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbHostValueFromSsmSecretAccessKeyValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbHostValueFromVault",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbHostValueFromVault)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbPassword",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbPassword)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbPasswordValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbPasswordValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbPasswordValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbPasswordValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbPasswordValueFromSsm",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbPasswordValueFromSsm)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbPasswordValueFromSsmAccessKeyId",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbPasswordValueFromSsmAccessKeyId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbPasswordValueFromSsmAccessKeyIdValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbPasswordValueFromSsmAccessKeyIdValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbPasswordValueFromSsmAccessKeyIdValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbPasswordValueFromSsmAccessKeyIdValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbPasswordValueFromSsmSecretAccessKey",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbPasswordValueFromSsmSecretAccessKey)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbPasswordValueFromSsmSecretAccessKeyValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbPasswordValueFromSsmSecretAccessKeyValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbPasswordValueFromSsmSecretAccessKeyValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbPasswordValueFromSsmSecretAccessKeyValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbPasswordValueFromVault",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbPasswordValueFromVault)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbPort",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbPort)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbPortValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbPortValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbPortValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbPortValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbPortValueFromSsm",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbPortValueFromSsm)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbPortValueFromSsmAccessKeyId",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbPortValueFromSsmAccessKeyId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbPortValueFromSsmAccessKeyIdValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbPortValueFromSsmAccessKeyIdValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbPortValueFromSsmAccessKeyIdValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbPortValueFromSsmAccessKeyIdValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbPortValueFromSsmSecretAccessKey",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbPortValueFromSsmSecretAccessKey)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbPortValueFromSsmSecretAccessKeyValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbPortValueFromSsmSecretAccessKeyValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbPortValueFromSsmSecretAccessKeyValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbPortValueFromSsmSecretAccessKeyValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbPortValueFromVault",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbPortValueFromVault)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbSchema",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbSchema)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbSchemaValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbSchemaValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbSchemaValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbSchemaValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbSchemaValueFromSsm",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbSchemaValueFromSsm)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbSchemaValueFromSsmAccessKeyId",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbSchemaValueFromSsmAccessKeyId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbSchemaValueFromSsmAccessKeyIdValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbSchemaValueFromSsmAccessKeyIdValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbSchemaValueFromSsmAccessKeyIdValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbSchemaValueFromSsmAccessKeyIdValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbSchemaValueFromSsmSecretAccessKey",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbSchemaValueFromSsmSecretAccessKey)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbSchemaValueFromSsmSecretAccessKeyValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbSchemaValueFromSsmSecretAccessKeyValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbSchemaValueFromSsmSecretAccessKeyValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbSchemaValueFromSsmSecretAccessKeyValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbSchemaValueFromVault",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbSchemaValueFromVault)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbSslmode",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbSslmode)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbSslmodeValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbSslmodeValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbSslmodeValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbSslmodeValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbSslmodeValueFromSsm",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbSslmodeValueFromSsm)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbSslmodeValueFromSsmAccessKeyId",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbSslmodeValueFromSsmAccessKeyId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbSslmodeValueFromSsmAccessKeyIdValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbSslmodeValueFromSsmAccessKeyIdValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbSslmodeValueFromSsmAccessKeyIdValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbSslmodeValueFromSsmAccessKeyIdValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbSslmodeValueFromSsmSecretAccessKey",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbSslmodeValueFromSsmSecretAccessKey)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbSslmodeValueFromSsmSecretAccessKeyValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbSslmodeValueFromSsmSecretAccessKeyValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbSslmodeValueFromSsmSecretAccessKeyValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbSslmodeValueFromSsmSecretAccessKeyValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbSslmodeValueFromVault",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbSslmodeValueFromVault)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbUri",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbUri)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbUriValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbUriValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbUriValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbUriValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbUriValueFromSsm",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbUriValueFromSsm)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbUriValueFromSsmAccessKeyId",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbUriValueFromSsmAccessKeyId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbUriValueFromSsmAccessKeyIdValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbUriValueFromSsmAccessKeyIdValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbUriValueFromSsmAccessKeyIdValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbUriValueFromSsmAccessKeyIdValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbUriValueFromSsmSecretAccessKey",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbUriValueFromSsmSecretAccessKey)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbUriValueFromSsmSecretAccessKeyValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbUriValueFromSsmSecretAccessKeyValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbUriValueFromSsmSecretAccessKeyValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbUriValueFromSsmSecretAccessKeyValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbUriValueFromVault",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbUriValueFromVault)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbUser",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbUser)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbUserValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbUserValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbUserValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbUserValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbUserValueFromSsm",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbUserValueFromSsm)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbUserValueFromSsmAccessKeyId",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbUserValueFromSsmAccessKeyId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbUserValueFromSsmAccessKeyIdValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbUserValueFromSsmAccessKeyIdValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbUserValueFromSsmAccessKeyIdValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbUserValueFromSsmAccessKeyIdValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbUserValueFromSsmSecretAccessKey",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbUserValueFromSsmSecretAccessKey)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbUserValueFromSsmSecretAccessKeyValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbUserValueFromSsmSecretAccessKeyValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbUserValueFromSsmSecretAccessKeyValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbUserValueFromSsmSecretAccessKeyValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionCockroachdbUserValueFromVault",
		reflect.TypeOf((*DatabaseSpecConnectionCockroachdbUserValueFromVault)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysql",
		reflect.TypeOf((*DatabaseSpecConnectionMysql)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlDbname",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlDbname)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlDbnameValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlDbnameValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlDbnameValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlDbnameValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlDbnameValueFromSsm",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlDbnameValueFromSsm)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlDbnameValueFromSsmAccessKeyId",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlDbnameValueFromSsmAccessKeyId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlDbnameValueFromSsmAccessKeyIdValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlDbnameValueFromSsmAccessKeyIdValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlDbnameValueFromSsmAccessKeyIdValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlDbnameValueFromSsmAccessKeyIdValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlDbnameValueFromSsmSecretAccessKey",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlDbnameValueFromSsmSecretAccessKey)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlDbnameValueFromSsmSecretAccessKeyValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlDbnameValueFromSsmSecretAccessKeyValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlDbnameValueFromSsmSecretAccessKeyValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlDbnameValueFromSsmSecretAccessKeyValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlDbnameValueFromVault",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlDbnameValueFromVault)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlHost",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlHost)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlHostValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlHostValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlHostValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlHostValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlHostValueFromSsm",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlHostValueFromSsm)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlHostValueFromSsmAccessKeyId",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlHostValueFromSsmAccessKeyId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlHostValueFromSsmAccessKeyIdValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlHostValueFromSsmAccessKeyIdValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlHostValueFromSsmAccessKeyIdValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlHostValueFromSsmAccessKeyIdValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlHostValueFromSsmSecretAccessKey",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlHostValueFromSsmSecretAccessKey)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlHostValueFromSsmSecretAccessKeyValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlHostValueFromSsmSecretAccessKeyValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlHostValueFromSsmSecretAccessKeyValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlHostValueFromSsmSecretAccessKeyValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlHostValueFromVault",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlHostValueFromVault)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlPassword",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlPassword)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlPasswordValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlPasswordValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlPasswordValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlPasswordValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlPasswordValueFromSsm",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlPasswordValueFromSsm)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlPasswordValueFromSsmAccessKeyId",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlPasswordValueFromSsmAccessKeyId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlPasswordValueFromSsmAccessKeyIdValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlPasswordValueFromSsmAccessKeyIdValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlPasswordValueFromSsmAccessKeyIdValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlPasswordValueFromSsmAccessKeyIdValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlPasswordValueFromSsmSecretAccessKey",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlPasswordValueFromSsmSecretAccessKey)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlPasswordValueFromSsmSecretAccessKeyValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlPasswordValueFromSsmSecretAccessKeyValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlPasswordValueFromSsmSecretAccessKeyValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlPasswordValueFromSsmSecretAccessKeyValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlPasswordValueFromVault",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlPasswordValueFromVault)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlPort",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlPort)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlPortValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlPortValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlPortValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlPortValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlPortValueFromSsm",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlPortValueFromSsm)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlPortValueFromSsmAccessKeyId",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlPortValueFromSsmAccessKeyId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlPortValueFromSsmAccessKeyIdValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlPortValueFromSsmAccessKeyIdValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlPortValueFromSsmAccessKeyIdValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlPortValueFromSsmAccessKeyIdValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlPortValueFromSsmSecretAccessKey",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlPortValueFromSsmSecretAccessKey)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlPortValueFromSsmSecretAccessKeyValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlPortValueFromSsmSecretAccessKeyValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlPortValueFromSsmSecretAccessKeyValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlPortValueFromSsmSecretAccessKeyValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlPortValueFromVault",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlPortValueFromVault)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlUri",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlUri)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlUriValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlUriValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlUriValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlUriValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlUriValueFromSsm",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlUriValueFromSsm)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlUriValueFromSsmAccessKeyId",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlUriValueFromSsmAccessKeyId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlUriValueFromSsmAccessKeyIdValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlUriValueFromSsmAccessKeyIdValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlUriValueFromSsmAccessKeyIdValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlUriValueFromSsmAccessKeyIdValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlUriValueFromSsmSecretAccessKey",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlUriValueFromSsmSecretAccessKey)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlUriValueFromSsmSecretAccessKeyValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlUriValueFromSsmSecretAccessKeyValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlUriValueFromSsmSecretAccessKeyValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlUriValueFromSsmSecretAccessKeyValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlUriValueFromVault",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlUriValueFromVault)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlUser",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlUser)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlUserValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlUserValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlUserValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlUserValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlUserValueFromSsm",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlUserValueFromSsm)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlUserValueFromSsmAccessKeyId",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlUserValueFromSsmAccessKeyId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlUserValueFromSsmAccessKeyIdValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlUserValueFromSsmAccessKeyIdValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlUserValueFromSsmAccessKeyIdValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlUserValueFromSsmAccessKeyIdValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlUserValueFromSsmSecretAccessKey",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlUserValueFromSsmSecretAccessKey)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlUserValueFromSsmSecretAccessKeyValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlUserValueFromSsmSecretAccessKeyValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlUserValueFromSsmSecretAccessKeyValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlUserValueFromSsmSecretAccessKeyValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionMysqlUserValueFromVault",
		reflect.TypeOf((*DatabaseSpecConnectionMysqlUserValueFromVault)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgres",
		reflect.TypeOf((*DatabaseSpecConnectionPostgres)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresDbname",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresDbname)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresDbnameValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresDbnameValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresDbnameValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresDbnameValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresDbnameValueFromSsm",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresDbnameValueFromSsm)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresDbnameValueFromSsmAccessKeyId",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresDbnameValueFromSsmAccessKeyId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresDbnameValueFromSsmAccessKeyIdValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresDbnameValueFromSsmAccessKeyIdValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresDbnameValueFromSsmAccessKeyIdValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresDbnameValueFromSsmAccessKeyIdValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresDbnameValueFromSsmSecretAccessKey",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresDbnameValueFromSsmSecretAccessKey)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresDbnameValueFromSsmSecretAccessKeyValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresDbnameValueFromSsmSecretAccessKeyValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresDbnameValueFromSsmSecretAccessKeyValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresDbnameValueFromSsmSecretAccessKeyValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresDbnameValueFromVault",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresDbnameValueFromVault)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresHost",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresHost)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresHostValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresHostValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresHostValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresHostValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresHostValueFromSsm",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresHostValueFromSsm)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresHostValueFromSsmAccessKeyId",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresHostValueFromSsmAccessKeyId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresHostValueFromSsmAccessKeyIdValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresHostValueFromSsmAccessKeyIdValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresHostValueFromSsmAccessKeyIdValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresHostValueFromSsmAccessKeyIdValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresHostValueFromSsmSecretAccessKey",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresHostValueFromSsmSecretAccessKey)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresHostValueFromSsmSecretAccessKeyValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresHostValueFromSsmSecretAccessKeyValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresHostValueFromSsmSecretAccessKeyValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresHostValueFromSsmSecretAccessKeyValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresHostValueFromVault",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresHostValueFromVault)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresPassword",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresPassword)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresPasswordValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresPasswordValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresPasswordValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresPasswordValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresPasswordValueFromSsm",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresPasswordValueFromSsm)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresPasswordValueFromSsmAccessKeyId",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresPasswordValueFromSsmAccessKeyId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresPasswordValueFromSsmAccessKeyIdValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresPasswordValueFromSsmAccessKeyIdValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresPasswordValueFromSsmAccessKeyIdValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresPasswordValueFromSsmAccessKeyIdValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresPasswordValueFromSsmSecretAccessKey",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresPasswordValueFromSsmSecretAccessKey)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresPasswordValueFromSsmSecretAccessKeyValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresPasswordValueFromSsmSecretAccessKeyValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresPasswordValueFromSsmSecretAccessKeyValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresPasswordValueFromSsmSecretAccessKeyValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresPasswordValueFromVault",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresPasswordValueFromVault)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresPort",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresPort)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresPortValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresPortValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresPortValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresPortValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresPortValueFromSsm",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresPortValueFromSsm)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresPortValueFromSsmAccessKeyId",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresPortValueFromSsmAccessKeyId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresPortValueFromSsmAccessKeyIdValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresPortValueFromSsmAccessKeyIdValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresPortValueFromSsmAccessKeyIdValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresPortValueFromSsmAccessKeyIdValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresPortValueFromSsmSecretAccessKey",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresPortValueFromSsmSecretAccessKey)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresPortValueFromSsmSecretAccessKeyValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresPortValueFromSsmSecretAccessKeyValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresPortValueFromSsmSecretAccessKeyValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresPortValueFromSsmSecretAccessKeyValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresPortValueFromVault",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresPortValueFromVault)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresSchema",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresSchema)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresSchemaValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresSchemaValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresSchemaValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresSchemaValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresSchemaValueFromSsm",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresSchemaValueFromSsm)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresSchemaValueFromSsmAccessKeyId",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresSchemaValueFromSsmAccessKeyId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresSchemaValueFromSsmAccessKeyIdValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresSchemaValueFromSsmAccessKeyIdValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresSchemaValueFromSsmAccessKeyIdValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresSchemaValueFromSsmAccessKeyIdValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresSchemaValueFromSsmSecretAccessKey",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresSchemaValueFromSsmSecretAccessKey)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresSchemaValueFromSsmSecretAccessKeyValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresSchemaValueFromSsmSecretAccessKeyValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresSchemaValueFromSsmSecretAccessKeyValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresSchemaValueFromSsmSecretAccessKeyValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresSchemaValueFromVault",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresSchemaValueFromVault)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresSslmode",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresSslmode)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresSslmodeValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresSslmodeValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresSslmodeValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresSslmodeValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresSslmodeValueFromSsm",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresSslmodeValueFromSsm)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresSslmodeValueFromSsmAccessKeyId",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresSslmodeValueFromSsmAccessKeyId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresSslmodeValueFromSsmAccessKeyIdValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresSslmodeValueFromSsmAccessKeyIdValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresSslmodeValueFromSsmAccessKeyIdValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresSslmodeValueFromSsmAccessKeyIdValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresSslmodeValueFromSsmSecretAccessKey",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresSslmodeValueFromSsmSecretAccessKey)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresSslmodeValueFromSsmSecretAccessKeyValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresSslmodeValueFromSsmSecretAccessKeyValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresSslmodeValueFromSsmSecretAccessKeyValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresSslmodeValueFromSsmSecretAccessKeyValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresSslmodeValueFromVault",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresSslmodeValueFromVault)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresUri",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresUri)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresUriValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresUriValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresUriValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresUriValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresUriValueFromSsm",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresUriValueFromSsm)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresUriValueFromSsmAccessKeyId",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresUriValueFromSsmAccessKeyId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresUriValueFromSsmAccessKeyIdValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresUriValueFromSsmAccessKeyIdValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresUriValueFromSsmAccessKeyIdValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresUriValueFromSsmAccessKeyIdValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresUriValueFromSsmSecretAccessKey",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresUriValueFromSsmSecretAccessKey)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresUriValueFromSsmSecretAccessKeyValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresUriValueFromSsmSecretAccessKeyValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresUriValueFromSsmSecretAccessKeyValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresUriValueFromSsmSecretAccessKeyValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresUriValueFromVault",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresUriValueFromVault)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresUser",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresUser)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresUserValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresUserValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresUserValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresUserValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresUserValueFromSsm",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresUserValueFromSsm)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresUserValueFromSsmAccessKeyId",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresUserValueFromSsmAccessKeyId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresUserValueFromSsmAccessKeyIdValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresUserValueFromSsmAccessKeyIdValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresUserValueFromSsmAccessKeyIdValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresUserValueFromSsmAccessKeyIdValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresUserValueFromSsmSecretAccessKey",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresUserValueFromSsmSecretAccessKey)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresUserValueFromSsmSecretAccessKeyValueFrom",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresUserValueFromSsmSecretAccessKeyValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresUserValueFromSsmSecretAccessKeyValueFromSecretKeyRef",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresUserValueFromSsmSecretAccessKeyValueFromSecretKeyRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionPostgresUserValueFromVault",
		reflect.TypeOf((*DatabaseSpecConnectionPostgresUserValueFromVault)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecConnectionSqlite",
		reflect.TypeOf((*DatabaseSpecConnectionSqlite)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecSchemahero",
		reflect.TypeOf((*DatabaseSpecSchemahero)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecTemplate",
		reflect.TypeOf((*DatabaseSpecTemplate)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"databasesschemaheroio.DatabaseSpecTemplateMetadata",
		reflect.TypeOf((*DatabaseSpecTemplateMetadata)(nil)).Elem(),
	)
}
