apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cncf-demo-db-password
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: google
  target:
    name: cncf-demo-password
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: production-postgresql
