---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQLClaim
metadata:
  name: cncf-demo
spec:
  id: cncf-demo-db
  compositionSelector:
    matchLabels:
      provider: google-official
      db: postgresql
  parameters:
    version: "13"
    size: small
