---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: production-apps
  namespace: carvel-apps
spec:
  syncPeriod: 5m
  serviceAccountName: infra-provisioner-sa
  fetch:
  - git:
      url: https://github.com/vfarcic/cncf-demo
      ref: origin/main
      subPath: apps
  template:
  - ytt:
      ignoreUnknownComments: true
      paths:
      - "."
  deploy:
  - kapp: {}
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: production-infra
  namespace: carvel-apps
spec:
  syncPeriod: 5m
  serviceAccountName: infra-provisioner-sa
  fetch:
  - git:
      url: https://github.com/vfarcic/cncf-demo
      ref: origin/main
      subPath: infra
  template:
  - ytt:
      ignoreUnknownComments: true
      paths:
      - "."
  deploy:
  - kapp: {}