---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: cncf-demo
  namespace: carvel-apps
spec:
  syncPeriod: 1m
  serviceAccountName: infra-provisioner-sa
  fetch:
    - git:
        url: https://github.com/vfarcic/cncf-demo
        ref: origin/main
        subPath: yaml/prod
  template:
    - ytt:
        ignoreUnknownComments: true
        paths:
          - "."
  deploy:
    - kapp:
        rawOptions: ["--dangerous-allow-empty-list-of-resources=true"]
        intoNs: production
