---
apiVersion: v1
kind: Secret
metadata:
  name: ingress-nginx-values
  namespace: carvel-apps
stringData:
  ingress-nginx-values.yaml: |
    controller:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: ingress-nginx
  namespace: carvel-apps
spec:
  syncPeriod: 5m
  serviceAccountName: infra-provisioner-sa
  fetch:
  - helmChart:
      name: ingress-nginx
      repository:
        url: https://kubernetes.github.io/ingress-nginx
      version: 4.2.0
  template:
  - helmTemplate:
      namespace: ingress-nginx
      name: ingress-nginx
      valuesFrom:
      - secretRef:
          name: ingress-nginx-values
  deploy:
  - kapp: {}