---
apiVersion: v1
kind: Namespace
metadata:
  name: carvel-apps
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-provisioner-sa
  namespace: carvel-apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infra-provisioner-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: infra-provisioner-sa
  namespace: carvel-apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
---
apiVersion: v1
kind: Namespace
metadata:
  name: emissary
---
apiVersion: v1
kind: Namespace
metadata:
  name: projectcontour
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: schemahero-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
