---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: schema-hero
  namespace: carvel-apps
spec:
  syncPeriod: 5m
  serviceAccountName: infra-provisioner-sa
  fetch:
  - git:
      url: https://github.com/vfarcic/cncf-demo
      ref: origin/main
      subPath: schema-hero
  template:
  - ytt:
      ignoreUnknownComments: true
      paths:
      - "."
  deploy:
  - kapp:
      intoNs: schemahero-system
