apiVersion: devopstoolkit.live/v1alpha1
kind: AppClaim
metadata:
  name: silly-demo
  labels:
    app-owner: vfarcic
spec:
  id: silly-demo
  compositionSelector:
    matchLabels:
      type: backend
      location: local
  parameters:
    namespace: production
    image: ghcr.io/vfarcic/cncf-demo-app
    tag: FIXME
    port: 8080
    host: silly-demo.135.237.0.239.nip.io
    ingressClassName: contour
    db:
      secret: silly-demo-db-20250107185725
    repository:
      enabled: true
      name: cncf-demo-app
    ci:
      enabled: true
      tool: none
