apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: google
spec:
  provider:
      gcpsm:
        auth:
          secretRef:
            secretAccessKeySecretRef:
              name: google
              key: credentials
              namespace: external-secrets
        projectID: MY_PROJECT_ID
