---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cncf-demo
  namespace: production
spec:
  interval: 5m
  chart:
    spec:
      chart: helm/app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  releaseName: cncf-demo
  targetNamespace: production
  values:
    image:
      tag: latest
    ingress:
      host: cncf-demo.sillydemo.com
      className: nginx
    tls:
      enabled: false
    db:
      id: cncf-demo-db
      enabled:
        crossplane:
          google: false
          aws: false
          azure: false
      size: small
      insecure: true
    schemahero:
      enabled: true
    replicas: 1
    fga:
      enabled: false
      storeId: STORE_ID
      modeId: MODEL_ID
    otel:
      enabled: false
    debug:
      enabled: false